id: P005529
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:56:38.315679
source_metadata:
  id: bdr:W1KG2808
  title: བདུད་འཇོམས་ཁྲོས་མའི་སྐོར
  author: ''
  volumes:
    ea4c970c5d3a4ef0a745f2454aee40e3:
      image_group_id: I1KG3151
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
